
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: shortlist-backend-container

    ports:
      - "8000:8000"

    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: shortlist-frontend-container

    ports:
      - "5173:80"